"""Market-data loader and microstructure tests.

The shape of this file follows `tests/test_indicators.py`: assert the property
that would actually be violated by the bug, against real artefacts rather than
mocks. Where that file checks RSI against Wilder's published worked example,
this one checks every rejection path against a file in `data/anomalies/` that is
broken on purpose — a mock that raises the exception you wrote it to raise
proves nothing about a vendor file.

The three claims worth stating plainly, because they are what the whole module
is for:

1. **Nothing is fabricated.** A one-sided or crossed book yields ``None``, not a
   mid. A notional larger than the visible book yields ``None``, not the last
   level's price extrapolated.
2. **Nothing is dropped silently.** Every refused row comes back with a line
   number and a reason, and the good rows around it survive.
3. **The future is unreachable, not merely unused.** ``replay`` is checked
   against an independently computed truncation of the event stream, so the
   test would fail if the iterator leaked so much as one event.

Everything here is offline. The corpus is generated by `tools/make_dataset.py`
and is shipped in the repository; no test reaches the network.
"""
from __future__ import annotations

import ast
import gzip
import io
import json
import math
import os
import sys

import numpy as np
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import market_data as md  # noqa: E402
from market_data import (  # noqa: E402
    BookEvent, BookIntegrityError, BookState, MarketDataError, RejectionReason,
)

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, "data")
OHLCV_BTC = os.path.join(DATA, "ohlcv", "BYBIT_SPOT_BTC_USDT_1H.csv.gz")
OHLCV_ETH = os.path.join(DATA, "ohlcv", "BYBIT_SPOT_ETH_USDT_1H.csv.gz")
OHLCV_SOL = os.path.join(DATA, "ohlcv", "BYBIT_SPOT_SOL_USDT_1H.csv.gz")
BOOK_BTC = os.path.join(DATA, "orderbook", "BYBIT_SPOT_BTC_USDT_L2.csv.gz")
QUOTES_BTC = os.path.join(DATA, "quotes", "BYBIT_SPOT_BTC_USDT_QUOTES.csv.gz")

pytestmark = pytest.mark.skipif(
    not os.path.exists(os.path.join(DATA, "MANIFEST.json")),
    reason="corpus not generated; run python3 tools/make_dataset.py",
)


# ---------------------------------------------------------------------------
# fixtures — the big files are parsed once for the whole session
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def manifest():
    with open(os.path.join(DATA, "MANIFEST.json"), encoding="utf-8") as handle:
        return json.load(handle)


@pytest.fixture(scope="session")
def btc_bars():
    return md.load_ohlcv(OHLCV_BTC)


@pytest.fixture(scope="session")
def btc_events():
    return md.load_book_events(BOOK_BTC)


@pytest.fixture(scope="session")
def btc_quotes():
    return md.load_quotes(QUOTES_BTC)


def ev(when, is_buy, price, size, kind, received=None, symbol="SYM"):
    """One book event. ``received`` defaults to ``when`` (zero latency)."""
    return BookEvent(symbol, when, when if received is None else received,
                     is_buy, price, size, kind)


def snapshot(when, bids, asks, symbol="SYM"):
    """A snapshot batch: every row shares one ``time_exchange``."""
    return ([ev(when, True, px, sx, "SNAPSHOT", symbol=symbol) for px, sx in bids]
            + [ev(when, False, px, sx, "SNAPSHOT", symbol=symbol) for px, sx in asks])


def anomaly_cases():
    """Every anomaly fixture, from the manifest rather than a hardcoded list.

    Reading the expected reason out of the shipped manifest means the generator
    and the loader have to agree on the contract in writing. A hardcoded list
    here would let a fixture be renamed or dropped without any test noticing.
    """
    path = os.path.join(DATA, "MANIFEST.json")
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as handle:
        files = json.load(handle)["files"]
    return sorted(
        (relpath, entry["data_kind"], entry["expected_rejection"])
        for relpath, entry in files.items()
        if entry.get("kind") == "anomaly"
    )


LOADERS = {
    "ohlcv": md.load_ohlcv,
    "quotes": md.load_quotes,
    "book": md.load_book_events,
}


def rows_of(load):
    for attribute in ("bars", "quotes", "events"):
        if hasattr(load, attribute):
            return getattr(load, attribute)
    raise AssertionError(f"no data attribute on {load!r}")


# ---------------------------------------------------------------------------
# timestamps
# ---------------------------------------------------------------------------


class TestTimestamps:
    def test_parses_the_seven_digit_coinapi_form(self):
        assert md.parse_timestamp("2024-03-01T00:00:00.0000000Z") == 1_709_251_200_000_000

    def test_round_trips_through_format(self):
        for text in ("2024-03-01T00:00:00.0000000Z",
                     "2024-02-29T23:59:59.9999990Z",
                     "2025-12-31T12:34:56.1234560Z"):
            assert md.format_timestamp(md.parse_timestamp(text)) == text

    def test_the_fast_path_agrees_with_the_regex_path(self):
        """The 28-char fast path must not accept or compute anything different.

        A fast path that disagrees with the strict parser is a way to smuggle a
        malformed timestamp past validation, so this compares them directly by
        forcing the slow path with a leading space.
        """
        for text in ("2024-03-01T00:00:00.5327850Z",
                     "2024-07-04T18:22:09.0000010Z",
                     "2024-12-31T23:59:59.9999999Z"):
            assert md.parse_timestamp(text) == md.parse_timestamp(" " + text)

    def test_leap_day_is_handled(self):
        assert md.parse_timestamp("2024-02-29T00:00:00.0000000Z") > 0
        with pytest.raises(MarketDataError):
            md.parse_timestamp("2023-02-29T00:00:00.0000000Z")

    def test_a_missing_z_is_rejected_not_assumed_utc(self):
        """Assuming UTC on an unmarked timestamp shifts a whole series silently."""
        with pytest.raises(MarketDataError):
            md.parse_timestamp("2024-03-01T00:00:00.0000000")

    def test_an_offset_timezone_is_rejected(self):
        with pytest.raises(MarketDataError):
            md.parse_timestamp("2024-03-01T00:00:00.0000000+02:00")

    @pytest.mark.parametrize("spelling", ["Z", "+00:00", "+0000"])
    def test_every_spelling_of_utc_gives_the_same_instant(self, spelling):
        """`+00:00` is UTC. Slice 38: refusing it silently dropped 571 bars.

        The corpus extension the human shipped writes `+00:00` where the older
        rows write `Z`. `load_ohlcv` rejected all 571 new bars as BAD_TIMESTAMP
        while the intake report went on calling the corpus 3,135 bars and
        eligible — the measurement would have run on the old truncated window
        and been written up as the full history.
        """
        assert (md.parse_timestamp("2024-03-01T00:00:00.0000000" + spelling)
                == md.parse_timestamp("2024-03-01T00:00:00.0000000Z"))

    @pytest.mark.parametrize("offset", ["+02:00", "-05:00", "+0530", "-00:00"])
    def test_a_non_utc_offset_is_still_rejected(self, offset):
        """The widening is one more spelling of UTC, not a conversion.

        `-00:00` is in this list deliberately: RFC 3339 gives it the meaning
        "the local offset is unknown", which is not a claim of UTC, and this
        parser does not guess.
        """
        with pytest.raises(MarketDataError):
            md.parse_timestamp("2024-03-01T00:00:00.0000000" + offset)

    def test_the_fast_path_and_the_regex_agree(self):
        """The 28-character fast path must not accept more than the regex.

        It is only reachable for the `Z` form, so the `+00:00` form has to go
        through the general path — and both have to produce the same integer.
        """
        canonical = "2024-03-01T00:00:00.0000000Z"
        assert len(canonical) == 28
        assert (md.parse_timestamp(canonical)
                == md.parse_timestamp("2024-03-01T00:00:00+00:00")
                == 1_709_251_200_000_000)


class TestTradesCountIsTheOnlyOptionalColumn:
    """Slice 38. A blank `trades_count` is "not reported"; a blank price is a bug.

    The Bitstamp extension leaves `trades_count` empty where the older rows
    write `0`. That column is 0 for all 2,564 original bars — the 1-minute
    archive does not report it — so a blank carries the same information,
    spelled honestly. Nothing reads it. Every other column stays fatal.
    """

    def _row(self, **overrides):
        cells = {"time_period_start": "2024-03-01T00:00:00.0000000Z",
                 "time_period_end": "2024-03-02T00:00:00.0000000Z",
                 "time_open": "2024-03-01T00:00:00.0000000Z",
                 "time_close": "2024-03-01T23:59:00.0000000Z",
                 "price_open": "100", "price_high": "110",
                 "price_low": "90", "price_close": "105",
                 "volume_traded": "12.5", "trades_count": "0"}
        cells.update(overrides)
        return ",".join(cells[c] for c in (
            "time_period_start", "time_period_end", "time_open", "time_close",
            "price_open", "price_high", "price_low", "price_close",
            "volume_traded", "trades_count"))

    def _load(self, tmp_path, row):
        header = ("time_period_start,time_period_end,time_open,time_close,"
                  "price_open,price_high,price_low,price_close,volume_traded,"
                  "trades_count")
        path = tmp_path / "one.csv"
        path.write_text(header + "\n" + row + "\n")
        return md.load_ohlcv(str(path))

    def test_a_blank_trades_count_loads_as_zero(self, tmp_path):
        load = self._load(tmp_path, self._row(trades_count=""))
        assert len(load.bars) == 1
        assert load.rejections == []
        assert load.bars[0].trades == 0

    def test_a_blank_close_is_still_fatal(self, tmp_path):
        """The decisive contrast. An empty close becoming 0.0 is the bug this
        loader exists to catch, and a blank cell is indistinguishable from a
        truncated write."""
        load = self._load(tmp_path, self._row(price_close=""))
        assert load.bars == []
        assert len(load.rejections) == 1

    @pytest.mark.parametrize("column", ["price_open", "price_high",
                                        "price_low", "volume_traded"])
    def test_every_other_blank_numeric_column_is_fatal(self, tmp_path, column):
        load = self._load(tmp_path, self._row(**{column: ""}))
        assert load.bars == []
        assert len(load.rejections) == 1

    def test_a_populated_trades_count_is_still_read(self, tmp_path):
        load = self._load(tmp_path, self._row(trades_count="4242"))
        assert load.bars[0].trades == 4242

    def test_a_nonsense_trades_count_is_still_fatal(self, tmp_path):
        """"Empty" is a value. "banana" is corruption."""
        load = self._load(tmp_path, self._row(trades_count="banana"))
        assert load.bars == []

    def test_a_negative_trades_count_is_still_fatal(self, tmp_path):
        load = self._load(tmp_path, self._row(trades_count="-1"))
        assert load.bars == []

    def test_out_of_range_fields_are_rejected(self):
        for text in ("2024-13-01T00:00:00.0000000Z",
                     "2024-03-32T00:00:00.0000000Z",
                     "2024-03-01T25:00:00.0000000Z"):
            with pytest.raises(MarketDataError):
                md.parse_timestamp(text)

    def test_sub_microsecond_digits_truncate_rather_than_round(self):
        """Rounding up could move an event across a bar close, which is the one
        boundary the no-lookahead cut depends on."""
        assert (md.parse_timestamp("2024-03-01T00:00:00.0000009Z")
                == md.parse_timestamp("2024-03-01T00:00:00.0000000Z"))

    def test_a_non_string_is_rejected(self):
        with pytest.raises(MarketDataError):
            md.parse_timestamp(1_709_251_200)


# ---------------------------------------------------------------------------
# rejection paths — against the fixtures that are broken on purpose
# ---------------------------------------------------------------------------


class TestRejectionPaths:
    @pytest.mark.parametrize("relpath,kind,expected", anomaly_cases())
    def test_the_declared_rejection_fires(self, relpath, kind, expected):
        """Each fixture must produce exactly the reason the manifest declares."""
        load = LOADERS[kind](os.path.join(DATA, relpath))
        reasons = [rejection.reason for rejection in load.rejections]
        assert reasons == [expected], (
            f"{relpath}: expected exactly [{expected}], got {reasons}"
        )

    @pytest.mark.parametrize("relpath,kind,expected", anomaly_cases())
    def test_the_good_rows_survive_the_bad_one(self, relpath, kind, expected):
        """One bad row must not take the file down with it.

        Each fixture holds two genuinely valid rows plus one defect. A loader
        that aborts the whole file on the first problem is a different bug, and
        it is the one that makes people disable validation.
        """
        load = LOADERS[kind](os.path.join(DATA, relpath))
        assert len(rows_of(load)) >= 2

    @pytest.mark.parametrize("relpath,kind,expected", anomaly_cases())
    def test_the_rejection_carries_a_line_number_and_the_raw_row(
            self, relpath, kind, expected):
        load = LOADERS[kind](os.path.join(DATA, relpath))
        rejection = load.rejections[0]
        assert rejection.line >= 2, "line 1 is the header"
        assert rejection.raw, "the offending row must come back with the rejection"
        assert rejection.detail, "a reason code without a detail is not diagnosable"
        assert relpath.split("/")[-1] in str(rejection)

    @pytest.mark.parametrize("relpath,kind,expected", anomaly_cases())
    def test_strict_mode_raises_instead_of_collecting(self, relpath, kind, expected):
        with pytest.raises(MarketDataError) as excinfo:
            LOADERS[kind](os.path.join(DATA, relpath), strict=True)
        assert expected in str(excinfo.value)

    @pytest.mark.parametrize("relpath,kind,expected", anomaly_cases())
    def test_raise_if_rejected_refuses_the_load(self, relpath, kind, expected):
        load = LOADERS[kind](os.path.join(DATA, relpath))
        with pytest.raises(MarketDataError):
            load.raise_if_rejected()

    def test_every_declared_rejection_reason_is_in_the_vocabulary(self):
        for _relpath, _kind, expected in anomaly_cases():
            assert expected in RejectionReason.ALL

    def test_the_reason_vocabulary_is_complete(self):
        """`ALL` must list every constant, or a caller cannot enumerate them."""
        declared = {
            value for name, value in vars(RejectionReason).items()
            if name.isupper() and name != "ALL" and isinstance(value, str)
        }
        assert declared == set(RejectionReason.ALL)

    def test_a_wrong_header_is_fatal_not_five_thousand_rejections(self, tmp_path):
        """Every row would fail identically, which buries the one useful fact."""
        path = tmp_path / "wrong.csv"
        path.write_text("open,high,low,close\n1,2,0.5,1.5\n", encoding="utf-8")
        with pytest.raises(MarketDataError) as excinfo:
            md.load_ohlcv(str(path))
        assert "header" in str(excinfo.value).lower()

    def test_a_reordered_header_is_rejected(self, tmp_path):
        """These loaders read by position; a reordered file would parse cleanly
        into nonsense."""
        columns = list(md._OHLCV_COLUMNS)
        columns[4], columns[5] = columns[5], columns[4]
        path = tmp_path / "reordered.csv"
        path.write_text(",".join(columns) + "\n", encoding="utf-8")
        with pytest.raises(MarketDataError):
            md.load_ohlcv(str(path))

    def test_an_empty_file_is_rejected(self, tmp_path):
        path = tmp_path / "empty.csv"
        path.write_bytes(b"")
        with pytest.raises(MarketDataError):
            md.load_ohlcv(str(path))

    def test_rejection_reasons_are_counted_for_logging(self):
        load = md.load_ohlcv(os.path.join(DATA, "anomalies",
                                          "ohlcv_duplicate_timestamp.csv"))
        assert load.rejection_reasons == {RejectionReason.DUPLICATE_TIMESTAMP: 1}
        assert load.ok is False

    def test_a_clean_file_reports_ok(self, btc_bars):
        assert btc_bars.ok
        assert btc_bars.rejections == []

    def test_the_load_result_is_not_iterable(self, btc_bars):
        """Deliberate: `for bar in load_ohlcv(path)` must not work.

        If it did, a caller could consume the bars and never learn that rows
        were refused. Reaching for `.bars` is what puts `.rejections` in the
        same line of sight.
        """
        with pytest.raises(TypeError):
            iter(btc_bars)

    def test_duplicate_and_out_of_order_are_different_reasons(self):
        """A double-delivered message and an unsorted file need different fixes."""
        duplicate = md.load_ohlcv(
            os.path.join(DATA, "anomalies", "ohlcv_duplicate_timestamp.csv"))
        inverted = md.load_ohlcv(
            os.path.join(DATA, "anomalies", "ohlcv_out_of_order.csv"))
        assert duplicate.rejections[0].reason == RejectionReason.DUPLICATE_TIMESTAMP
        assert inverted.rejections[0].reason == RejectionReason.NON_MONOTONIC_TIMESTAMP

    def test_rows_are_not_sorted_before_checking(self):
        """Sorting first would repair the file and destroy the evidence."""
        load = md.load_ohlcv(
            os.path.join(DATA, "anomalies", "ohlcv_out_of_order.csv"))
        assert load.rejections, "an unordered source must be reported, not tidied"

    def test_an_interval_mismatch_is_its_own_reason(self):
        load = md.load_ohlcv(OHLCV_BTC, expected_interval_seconds=900)
        assert load.bars == []
        assert set(load.rejection_reasons) == {RejectionReason.INTERVAL_MISMATCH}

    def test_the_expected_interval_passes_on_the_real_file(self, manifest):
        load = md.load_ohlcv(OHLCV_BTC, expected_interval_seconds=3_600)
        assert load.ok and len(load.bars) == manifest["bars_per_symbol"]


# ---------------------------------------------------------------------------
# OHLCV invariants on the shipped corpus
# ---------------------------------------------------------------------------


class TestOhlcvCorpus:
    @pytest.mark.parametrize("path", [OHLCV_BTC, OHLCV_ETH, OHLCV_SOL])
    def test_loads_without_a_single_rejection(self, path):
        load = md.load_ohlcv(path)
        assert load.ok, load.rejection_reasons
        assert len(load.bars) == load.rows_read

    def test_high_and_low_bracket_open_and_close(self, btc_bars):
        for bar in btc_bars.bars:
            assert bar.high >= max(bar.open, bar.close)
            assert bar.low <= min(bar.open, bar.close)

    def test_consecutive_bars_are_gap_consistent(self, btc_bars):
        """Each bar opens exactly where the previous one closed.

        The generator measures OHLC from a continuous tick path, so this is a
        real property of the data — and it is what makes the backtester's
        intrabar stop logic meaningful rather than an artefact of invented gaps.
        """
        bars = btc_bars.bars
        for previous, current in zip(bars, bars[1:]):
            assert current.open == pytest.approx(previous.close, rel=1e-12)

    def test_timestamps_are_strictly_increasing_and_evenly_spaced(self, btc_bars):
        bars = btc_bars.bars
        deltas = {b.open_us - a.open_us for a, b in zip(bars, bars[1:])}
        assert deltas == {3_600_000_000}

    def test_prices_are_positive_and_volume_is_not_negative(self, btc_bars):
        for bar in btc_bars.bars:
            assert min(bar.open, bar.high, bar.low, bar.close) > 0
            assert bar.volume >= 0 and bar.trades >= 0

    def test_bars_are_positionally_compatible_with_backtest_bar(self):
        """The compatibility claim in the module docstring, asserted.

        `market_data` must not import `backtest` (that would invert the
        dependency graph), so the compatibility is structural — and structural
        compatibility rots silently unless something checks it. The test may
        import both; the module may not.
        """
        import dataclasses

        import backtest

        theirs = [f.name for f in dataclasses.fields(backtest.Bar)]
        ours = [f.name for f in dataclasses.fields(md.Bar)]
        assert ours[:len(theirs)] == theirs, (
            "market_data.Bar no longer matches backtest.Bar positionally"
        )

    def test_a_loaded_bar_can_be_used_as_a_backtest_bar(self, btc_bars):
        import backtest

        bar = btc_bars.bars[0]
        assert bar.as_kline_row() == backtest.Bar(
            bar.start_ms, bar.open, bar.high, bar.low, bar.close, bar.volume
        ).as_kline_row()

    def test_close_series_feeds_the_indicators(self, btc_bars):
        """The point of the corpus: real-shaped input for the real math."""
        import pure_indicators as pi

        closes = btc_bars.closes()[:400]
        assert closes.shape == (400,)
        assert 0.0 <= float(pi.rsi(closes, 14)[-1]) <= 100.0

    def test_loading_is_deterministic(self):
        first = md.load_ohlcv(OHLCV_BTC).bars
        second = md.load_ohlcv(OHLCV_BTC).bars
        assert first == second

    def test_volume_is_autocorrelated_not_iid(self, btc_bars):
        """Clustered volume is the whole reason to model it.

        Anything that normalises by recent volume behaves differently against an
        i.i.d. series than against a real one, and would look better here than
        it will live.
        """
        volumes = np.array([bar.volume for bar in btc_bars.bars])
        centred = volumes - volumes.mean()
        lag1 = float((centred[:-1] * centred[1:]).sum() / (centred ** 2).sum())
        assert lag1 > 0.2, f"volume looks i.i.d. (lag-1 autocorrelation {lag1:.3f})"


# ---------------------------------------------------------------------------
# BookState — one test per update type, plus the batching rule
# ---------------------------------------------------------------------------


class TestBookStateUpdates:
    def test_snapshot_builds_both_sides(self):
        state = BookState("SYM").apply_all(
            snapshot(1_000, [(100.0, 2.0), (99.0, 3.0)], [(101.0, 1.0), (102.0, 4.0)])
        )
        assert [level.price for level in state.bids] == [100.0, 99.0]
        assert [level.price for level in state.asks] == [101.0, 102.0]

    def test_a_snapshot_batch_is_delimited_by_its_timestamp(self):
        """Forty rows are one snapshot, not forty replacements.

        Treating each row as "replace the book" leaves a one-level book after
        every snapshot; keying the reset on a change of time_exchange is what
        the exchange actually means.
        """
        state = BookState("SYM")
        state.apply_all(snapshot(1_000, [(100.0, 2.0), (99.0, 3.0)], [(101.0, 1.0)]))
        assert len(state.bids) == 2 and state.snapshots_seen == 1
        state.apply_all(snapshot(2_000, [(90.0, 1.0)], [(91.0, 1.0)]))
        assert [level.price for level in state.bids] == [90.0], "a new snapshot replaces"
        assert state.snapshots_seen == 2

    def test_set_replaces_a_level(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 7.5, "SET"))
        assert state.best_bid.size == 7.5

    def test_set_with_zero_size_removes_the_level(self):
        """The CoinAPI convention. Rejecting it would leave the book too deep —
        and a book that is too deep understates slippage."""
        state = BookState("SYM").apply_all(
            snapshot(1, [(100.0, 2.0), (99.0, 1.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 0.0, "SET"))
        assert state.best_bid.price == 99.0

    def test_add_increases_an_existing_level(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 1.5, "ADD"))
        assert state.best_bid.size == pytest.approx(3.5)

    def test_add_creates_a_missing_level(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.5, 1.0, "ADD"))
        assert state.best_bid == (100.5, 1.0)

    def test_sub_decreases_a_level(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 0.5, "SUB"))
        assert state.best_bid.size == pytest.approx(1.5)

    def test_sub_to_zero_removes_the_level(self):
        state = BookState("SYM").apply_all(
            snapshot(1, [(100.0, 2.0), (99.0, 1.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 2.0, "SUB"))
        assert state.best_bid.price == 99.0

    def test_match_consumes_and_is_counted_separately_from_sub(self):
        """MATCH is flow; SUB is a cancellation. Same arithmetic, different fact."""
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 0.5, "MATCH"))
        assert state.best_bid.size == pytest.approx(1.5)
        assert state.matched_base == pytest.approx(0.5)
        state.apply(ev(3, True, 100.0, 0.5, "SUB"))
        assert state.matched_base == pytest.approx(0.5), "SUB is not traded volume"

    def test_delete_removes_the_level_regardless_of_size(self):
        state = BookState("SYM").apply_all(
            snapshot(1, [(100.0, 2.0), (99.0, 1.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 0.0, "DELETE"))
        assert [level.price for level in state.bids] == [99.0]

    def test_oversubtraction_raises_by_default(self):
        """Divergence from the exchange's book is fatal, not clamped.

        Clamping produces a book that is wrong by an unknown amount for an
        unknown duration, which is worse than a loud stop.
        """
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        with pytest.raises(BookIntegrityError):
            state.apply(ev(2, True, 100.0, 5.0, "SUB"))

    def test_oversubtraction_can_be_clamped_but_is_recorded(self):
        state = BookState("SYM", strict=False)
        state.apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        state.apply(ev(2, True, 100.0, 5.0, "SUB"))
        assert state.best_bid is None
        assert len(state.integrity_warnings) == 1

    def test_subtracting_from_a_missing_level_is_an_integrity_error(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        with pytest.raises(BookIntegrityError):
            state.apply(ev(2, True, 42.0, 1.0, "MATCH"))

    def test_an_out_of_order_event_is_refused(self):
        """Replaying a book out of order produces a state that never existed."""
        state = BookState("SYM").apply_all(snapshot(1_000, [(100.0, 2.0)], [(101.0, 1.0)]))
        with pytest.raises(BookIntegrityError):
            state.apply(ev(999, True, 100.0, 1.0, "SET"))

    def test_an_event_for_another_symbol_is_refused(self):
        state = BookState("BTC").apply_all(
            snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)], symbol="BTC"))
        with pytest.raises(BookIntegrityError):
            state.apply(ev(2, True, 100.0, 1.0, "SET", symbol="ETH"))

    def test_an_unknown_update_type_is_refused(self):
        state = BookState("SYM")
        with pytest.raises(BookIntegrityError):
            state.apply(ev(1, True, 100.0, 1.0, "REPLACE"))

    def test_bids_sort_descending_and_asks_ascending(self):
        state = BookState("SYM").apply_all(snapshot(
            1, [(99.0, 1.0), (101.0, 1.0), (100.0, 1.0)],
            [(105.0, 1.0), (103.0, 1.0), (104.0, 1.0)]))
        assert [level.price for level in state.bids] == [101.0, 100.0, 99.0]
        assert [level.price for level in state.asks] == [103.0, 104.0, 105.0]

    def test_a_copy_is_detached(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], [(101.0, 1.0)]))
        clone = state.copy()
        clone.apply(ev(2, True, 100.0, 9.0, "SET"))
        assert state.best_bid.size == 2.0, "mutating a copy must not reach the original"


# ---------------------------------------------------------------------------
# features — the refusals matter more than the numbers
# ---------------------------------------------------------------------------


def two_sided(bid=100.0, bid_size=2.0, ask=101.0, ask_size=1.0):
    return BookState("SYM").apply_all(
        snapshot(1, [(bid, bid_size)], [(ask, ask_size)]))


class TestBookFeatures:
    def test_mid_is_the_average_of_the_touch(self):
        assert two_sided().features().mid == pytest.approx(100.5)

    def test_an_empty_book_has_no_mid(self):
        features = BookState("SYM").features()
        assert features.mid is None and features.usable is False
        assert "empty" in features.reason

    def test_a_one_sided_book_has_no_mid(self):
        """The exact failure this module exists to eliminate.

        A mid inferred from bids alone looks like a price, prices a position,
        and is a guess.
        """
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], []))
        features = state.features()
        assert features.mid is None
        assert features.best_bid == 100.0, "the side that exists is still reported"
        assert features.best_ask is None
        assert "ask" in features.reason

    def test_a_crossed_book_yields_no_mid(self):
        state = BookState("SYM").apply_all(snapshot(1, [(102.0, 1.0)], [(101.0, 1.0)]))
        features = state.features()
        assert state.is_crossed
        assert features.mid is None
        assert features.microprice is None
        assert features.spread_bps is None
        assert features.imbalance is None
        assert "crossed" in features.reason

    def test_a_locked_book_is_refused_too(self):
        """No spread to cross and no mid that is not also a touch."""
        state = BookState("SYM").apply_all(snapshot(1, [(101.0, 1.0)], [(101.0, 1.0)]))
        assert state.features().mid is None
        assert "locked" in state.features().reason

    def test_depth_is_still_reported_on_a_one_sided_book(self):
        """A one-sided sum is a true statement about the side it sums."""
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 2.0)], []))
        features = state.features()
        assert features.depth_bid_usd == pytest.approx(200.0)
        assert features.depth_ask_usd is None

    def test_microprice_leans_toward_the_thinner_side(self):
        """A big bid and a small ask means the next trade lifts the ask."""
        features = two_sided(bid_size=10.0, ask_size=1.0).features()
        assert features.mid == pytest.approx(100.5)
        assert features.microprice > features.mid

    def test_microprice_is_symmetric(self):
        features = two_sided(bid_size=1.0, ask_size=10.0).features()
        assert features.microprice < features.mid

    def test_microprice_equals_mid_when_the_touch_is_balanced(self):
        assert two_sided(bid_size=3.0, ask_size=3.0).features().microprice \
            == pytest.approx(100.5)

    def test_spread_bps_is_measured_against_mid(self):
        features = two_sided(bid=100.0, ask=101.0).features()
        assert features.spread_bps == pytest.approx(1.0 / 100.5 * 10_000)

    def test_depth_sums_notional_to_n_levels(self):
        state = BookState("SYM").apply_all(snapshot(
            1, [(100.0, 1.0), (99.0, 1.0), (98.0, 1.0)],
            [(101.0, 1.0), (102.0, 1.0)]))
        assert state.features(levels=2).depth_bid_usd == pytest.approx(199.0)
        assert state.features(levels=3).depth_bid_usd == pytest.approx(297.0)

    def test_levels_must_be_at_least_one(self):
        with pytest.raises(ValueError):
            two_sided().features(levels=0)

    def test_imbalance_is_bounded(self):
        for bid_size, ask_size in ((1e9, 1e-9), (1e-9, 1e9), (1.0, 1.0)):
            imbalance = two_sided(bid_size=bid_size, ask_size=ask_size)\
                .features().imbalance
            assert -1.0 <= imbalance <= 1.0

    def test_imbalance_is_positive_when_bids_dominate(self):
        assert two_sided(bid_size=10.0, ask_size=1.0).features().imbalance > 0

    def test_imbalance_is_zero_on_a_balanced_book(self):
        features = two_sided(bid=100.0, bid_size=1.0, ask=100.0 + 1e-9,
                             ask_size=1.0).features()
        assert features.imbalance == pytest.approx(0.0, abs=1e-6)

    def test_imbalance_over_the_whole_corpus_stays_in_range(self, btc_bars, btc_events):
        seen = 0
        for step in md.replay(btc_bars.bars[:300], btc_events.events, levels=10):
            if step.features.imbalance is not None:
                seen += 1
                assert -1.0 <= step.features.imbalance <= 1.0
        assert seen > 100

    def test_an_anomalous_spread_is_flagged_not_silently_used(self):
        features = two_sided(bid=50.0, ask=150.0).features()
        assert features.anomalous_spread is True
        assert features.spread_bps is not None, "flagged, but still measured"

    def test_a_normal_spread_is_not_flagged(self):
        assert two_sided().features().anomalous_spread is False


# ---------------------------------------------------------------------------
# slippage
# ---------------------------------------------------------------------------


def laddered_book(levels=5, base=100.0, step=1.0, size=1.0):
    """A book with equal size on every level, symmetric around ``base``."""
    bids = [(base - step * (i + 1), size) for i in range(levels)]
    asks = [(base + step * (i + 1), size) for i in range(levels)]
    return BookState("SYM").apply_all(snapshot(1, bids, asks))


class TestSlippage:
    def test_a_touch_sized_order_costs_the_half_spread(self):
        features = laddered_book().features()
        notional = features.ask_levels[0].notional
        assert features.slippage_bps_for(notional, "BUY") == pytest.approx(
            (101.0 - 100.0) / 100.0 * 10_000
        )

    def test_slippage_grows_with_size(self):
        features = laddered_book(levels=5, size=1.0).features()
        costs = [features.slippage_bps_for(n, "BUY") for n in (101, 250, 400, 500)]
        assert all(cost is not None for cost in costs)
        assert costs == sorted(costs), f"slippage must not fall with size: {costs}"
        assert costs[-1] > costs[0]

    def test_slippage_is_never_negative_on_an_uncrossed_book(self):
        """A negative cost would mean the book paid you to trade."""
        features = laddered_book().features()
        for side in ("BUY", "SELL"):
            for notional in (50, 150, 300):
                assert features.slippage_bps_for(notional, side) >= 0.0

    def test_buy_and_sell_are_comparable_on_a_symmetric_book(self):
        """Roughly equal, not exactly.

        The levels are symmetric in *size* but sit at different absolute prices
        (99, 98, 97 against 101, 102, 103), so a fixed notional buys fewer units
        going up than going down and the two VWAPs land a couple of percent
        apart. That residual is arithmetic, not a bug — demanding exact equality
        would only be satisfiable by a book that cannot exist.
        """
        features = laddered_book().features()
        assert features.slippage_bps_for(250, "BUY") == pytest.approx(
            features.slippage_bps_for(250, "SELL"), rel=0.05
        )

    def test_buying_walks_the_asks_and_selling_walks_the_bids(self):
        """Direction correctness: a thin ask makes buying expensive, not selling."""
        state = BookState("SYM").apply_all(snapshot(
            1, [(99.0, 100.0), (98.0, 100.0)], [(101.0, 0.05), (110.0, 100.0)]))
        features = state.features()
        assert features.slippage_bps_for(2_000, "BUY") > \
            features.slippage_bps_for(2_000, "SELL")

    def test_an_order_larger_than_the_book_returns_none(self):
        """Not the last level's price extrapolated.

        Running out of book is the case where real slippage is worst, so
        extrapolating understates the cost precisely when it matters most — and
        turns "your order is too big for this market" into a modest-looking
        number a sizing routine will act on.
        """
        features = laddered_book(levels=3, size=1.0).features()
        assert features.slippage_bps_for(10_000_000, "BUY") is None

    def test_fillable_notional_explains_a_none(self):
        features = laddered_book(levels=3, size=1.0).features()
        capacity = features.fillable_notional("BUY")
        assert features.slippage_bps_for(capacity * 0.9, "BUY") is not None
        assert features.slippage_bps_for(capacity * 1.1, "BUY") is None

    def test_a_crossed_book_returns_none_rather_than_a_cost(self):
        state = BookState("SYM").apply_all(snapshot(1, [(102.0, 5.0)], [(101.0, 5.0)]))
        assert state.features().slippage_bps_for(10.0, "BUY") is None

    def test_a_one_sided_book_returns_none(self):
        state = BookState("SYM").apply_all(snapshot(1, [(100.0, 5.0)], []))
        assert state.features().slippage_bps_for(10.0, "SELL") is None

    def test_a_non_positive_notional_raises(self):
        features = laddered_book().features()
        for bad in (0.0, -100.0, float("nan"), float("inf")):
            with pytest.raises(ValueError):
                features.slippage_bps_for(bad, "BUY")

    def test_an_unknown_side_raises(self):
        with pytest.raises(ValueError):
            laddered_book().features().slippage_bps_for(100.0, "sideways")

    def test_only_the_measured_levels_are_used(self):
        """`features(levels=1)` must not answer for size that level cannot hold."""
        state = laddered_book(levels=5, size=1.0)
        assert state.features(levels=1).slippage_bps_for(400, "BUY") is None
        assert state.features(levels=5).slippage_bps_for(400, "BUY") is not None

    def test_selling_into_the_crash_costs_far_more_than_in_calm(
            self, btc_bars, btc_events):
        """The reason to ship a book at all.

        The bid thins and the spread widens together, so a stop-loss — a market
        sell — is most expensive exactly when it fires. No constant-slippage
        backtest can see this.
        """
        calm, crash = [], []
        for step in md.replay(btc_bars.bars, btc_events.events, levels=10):
            cost = step.features.slippage_bps_for(50_000.0, "SELL")
            if cost is None:
                continue
            if step.index < 1_500:
                calm.append(cost)
            elif 2_700 <= step.index < 3_000:
                crash.append(cost)
        assert len(calm) > 500 and len(crash) > 100
        calm_mean = sum(calm) / len(calm)
        crash_mean = sum(crash) / len(crash)
        assert crash_mean > 5 * calm_mean, (
            f"crash slippage {crash_mean:.2f} bps vs calm {calm_mean:.2f} bps"
        )


# ---------------------------------------------------------------------------
# replay — the no-lookahead guarantee
# ---------------------------------------------------------------------------


class TestReplayCannotSeeTheFuture:
    def test_no_event_after_the_bar_close_is_ever_applied(self, btc_bars, btc_events):
        for step in md.replay(btc_bars.bars[:800], btc_events.events):
            assert step.last_event_us is None or step.last_event_us <= step.cutoff_us

    def test_the_book_matches_an_independently_truncated_stream(
            self, btc_bars, btc_events):
        """The strongest form of the claim.

        Rebuild the book from scratch out of only those events at or before the
        bar's close, computed without the iterator's help, and require the same
        touch. If `replay` leaked a single future event the two would differ.
        """
        events = btc_events.events
        for step in md.replay(btc_bars.bars[:40], events):
            truncated = BookState(events[0].symbol_id, strict=False)
            for event in events:
                if event.time_coinapi_us > step.cutoff_us:
                    break
                truncated.apply(event)
            assert truncated.best_bid == step.book.best_bid
            assert truncated.best_ask == step.book.best_ask

    def test_the_cut_is_on_receive_time_not_exchange_time(self, btc_bars, btc_events):
        """Cutting on time_exchange grants the collection latency as foresight.

        It is a few hundred microseconds here, which is exactly why it has to be
        right here: the same code against a feed with 400ms of latency would be
        reading the future by a whole trading decision.
        """
        bars = btc_bars.bars[:200]
        by_receive = [s.events_applied for s in md.replay(bars, btc_events.events)]
        by_exchange = [s.events_applied for s in
                       md.replay(bars, btc_events.events, use_coinapi_time=False)]
        assert by_exchange >= by_receive
        assert by_exchange != by_receive, (
            "the two cuts must differ, or the corpus has no latency to model"
        )

    def test_events_applied_only_ever_increases(self, btc_bars, btc_events):
        counts = [s.events_applied for s in md.replay(btc_bars.bars[:500],
                                                      btc_events.events)]
        assert counts == sorted(counts)

    def test_each_step_yields_a_detached_book(self, btc_bars, btc_events):
        """A consumer mutating the yielded book must not change the next step."""
        steps = []
        symbol = btc_events.events[0].symbol_id
        for step in md.replay(btc_bars.bars[:5], btc_events.events):
            steps.append(step)
            # Wipe the yielded book entirely. If the iterator were handing out
            # its own state, the next step would start from this rubble.
            step.book.apply(ev(step.cutoff_us + 1, True, 1.0, 999.0, "SNAPSHOT",
                               symbol=symbol))
        assert all(len(s.book.bids) == 1 for s in steps), "each was clobbered"
        for step in md.replay(btc_bars.bars[:5], btc_events.events):
            assert len(step.book.bids) > 1, "a later step inherited the damage"

    def test_one_step_per_bar_in_order(self, btc_bars, btc_events):
        bars = btc_bars.bars[:120]
        steps = list(md.replay(bars, btc_events.events))
        assert [s.index for s in steps] == list(range(len(bars)))
        assert [s.bar for s in steps] == bars

    def test_unsorted_events_are_refused_not_sorted(self, btc_bars, btc_events):
        """Sorting inside the replay would mask an unsorted — and probably
        incomplete — source."""
        events = list(btc_events.events[:500])
        events[100], events[300] = events[300], events[100]
        with pytest.raises(MarketDataError):
            list(md.replay(btc_bars.bars[:5], events))

    def test_unsorted_bars_are_refused(self, btc_bars, btc_events):
        bars = list(btc_bars.bars[:10])
        bars[3], bars[7] = bars[7], bars[3]
        with pytest.raises(MarketDataError):
            list(md.replay(bars, btc_events.events))

    def test_replay_works_with_bars_that_carry_only_millisecond_stamps(self):
        """`Bar` built the `backtest.Bar` way leaves start_us at 0.

        Without the fallback every such bar claims to start at the epoch and the
        whole series reads as non-monotonic.
        """
        bars = [md.Bar(1_709_251_200_000 + i * 3_600_000, 100.0, 101.0, 99.0,
                       100.5, 1.0) for i in range(3)]
        steps = list(md.replay(bars, []))
        assert len(steps) == 3
        assert steps[1].cutoff_us > steps[0].cutoff_us

    def test_replay_over_an_empty_event_stream_yields_empty_books(self, btc_bars):
        steps = list(md.replay(btc_bars.bars[:3], []))
        assert all(s.book.is_empty and s.features.mid is None for s in steps)

    def test_the_book_is_never_crossed_anywhere_in_the_shipped_stream(
            self, btc_bars, btc_events):
        """A crossed book must mean "something is wrong", not "the fixture is
        lazy". If the generator's sampling could leave stale levels crossing the
        new touch, every crossed-book test above would be testing the fixture.
        """
        crossed = 0
        for step in md.replay(btc_bars.bars, btc_events.events):
            if step.book.is_crossed:
                crossed += 1
        assert crossed == 0

    def test_the_shipped_stream_replays_without_a_single_integrity_warning(
            self, btc_bars, btc_events):
        """The generator's update semantics and the loader's must agree exactly."""
        last = None
        for step in md.replay(btc_bars.bars, btc_events.events, strict_book=True):
            last = step
        assert last is not None and last.book.integrity_warnings == []


# ---------------------------------------------------------------------------
# quotes
# ---------------------------------------------------------------------------


class TestQuotes:
    def test_the_shipped_quotes_load_clean(self, btc_quotes):
        assert btc_quotes.ok, btc_quotes.rejection_reasons
        assert len(btc_quotes.quotes) > 10_000

    def test_every_quote_is_uncrossed_with_size_on_both_sides(self, btc_quotes):
        for quote in btc_quotes.quotes:
            assert quote.bid_px < quote.ask_px
            assert quote.bid_sx > 0 and quote.ask_sx > 0

    def test_collection_latency_is_never_negative(self, btc_quotes):
        for quote in btc_quotes.quotes:
            assert quote.time_coinapi_us >= quote.time_exchange_us

    def test_spread_widens_in_the_crash(self, btc_quotes, manifest):
        """Spreads that widen when liquidity leaves are the point of the corpus."""
        spans = {r["name"]: (md.parse_timestamp(r["first_timestamp"]),
                             md.parse_timestamp(r["last_timestamp"]))
                 for r in manifest["files"][
                     "ohlcv/BYBIT_SPOT_BTC_USDT_1H.csv.gz"]["regimes"]}
        by_regime = {name: [] for name in spans}
        for quote in btc_quotes.quotes:
            for name, (start, end) in spans.items():
                if start <= quote.time_exchange_us < end:
                    by_regime[name].append(quote.spread_bps)
                    break
        calm = sum(by_regime["CALM_RANGE"]) / len(by_regime["CALM_RANGE"])
        crash = sum(by_regime["CRASH"]) / len(by_regime["CRASH"])
        assert crash > 10 * calm, f"crash {crash:.1f} bps vs calm {calm:.1f} bps"

    def test_quote_mid_and_microprice_refuse_a_crossed_quote(self):
        quote = md.Quote("SYM", 1, 2, ask_px=100.0, ask_sx=1.0,
                         bid_px=101.0, bid_sx=1.0)
        assert quote.mid is None
        assert quote.spread_bps is None
        assert quote.microprice is None

    def test_quote_mid_is_computed_on_a_normal_quote(self):
        quote = md.Quote("SYM", 1, 2, ask_px=101.0, ask_sx=1.0,
                         bid_px=100.0, bid_sx=1.0)
        assert quote.mid == pytest.approx(100.5)
        assert quote.microprice == pytest.approx(100.5)


# ---------------------------------------------------------------------------
# the anomaly filter
# ---------------------------------------------------------------------------


class TestAnomalyFilter:
    def test_the_threshold_is_the_configured_fraction(self):
        import config

        assert config.get_config_object().MAX_SPREAD_ANOMALY_PCT == 0.67

    def test_a_spread_beyond_the_limit_is_anomalous(self):
        assert md.is_spread_anomalous(50.0, 150.0) is True     # 100% of mid

    def test_a_spread_inside_the_limit_is_not(self):
        assert md.is_spread_anomalous(100.0, 101.0) is False

    def test_it_fails_closed_on_a_crossed_or_broken_quote(self):
        for bid, ask in ((101.0, 100.0), (0.0, 1.0), (1.0, float("nan")),
                         (-1.0, 1.0), (1.0, 1.0)):
            assert md.is_spread_anomalous(bid, ask) is True

    def test_the_limit_is_taken_from_the_config_object(self):
        class Tight:
            MAX_SPREAD_ANOMALY_PCT = 0.001

        assert md.is_spread_anomalous(100.0, 101.0, Tight()) is True

    def test_spread_bps_returns_none_rather_than_a_negative_credit(self):
        """A negative spread flows into a cost model as a reason to trade more."""
        assert md.spread_bps(101.0, 100.0) is None
        assert md.spread_bps(100.0, 101.0) > 0

    def test_prices_normalise_to_nine_decimals(self):
        assert md.normalize_price(1.0 / 3.0) == 0.333333333
        assert md.normalize_price(62_000.1234567891) == 62_000.123456789

    def test_normalisation_makes_level_identity_stable(self):
        """Two events meaning the same price must produce the same book key.

        `BookState` normalises on the way in rather than trusting the caller to
        have done it, so a hand-built event carrying 0.30000000000000004 lands
        on the same level as one carrying 0.3 — instead of quietly doubling the
        depth at that price.
        """
        state = BookState("SYM").apply_all(snapshot(1, [(0.3, 1.0)], [(1.0, 1.0)]))
        state.apply(ev(2, True, 0.1 + 0.2, 5.0, "SET"))
        assert 0.1 + 0.2 != 0.3, "the premise: these are different floats"
        assert len(state.bids) == 1 and state.best_bid.size == 5.0


# ---------------------------------------------------------------------------
# manifest
# ---------------------------------------------------------------------------


class TestManifest:
    def test_the_shipped_corpus_verifies(self):
        report = md.verify_manifest(DATA)
        assert report.ok, report.problems
        assert report.checked >= 19

    def test_a_deep_verification_also_counts_rows(self):
        report = md.verify_manifest(DATA, deep=True)
        assert report.ok, report.problems

    def test_the_manifest_declares_the_data_synthetic(self, manifest):
        """Provenance must survive a copy of the directory."""
        assert manifest["synthetic"] is True
        assert "SYNTHETIC" in manifest["warning"]
        assert md.verify_manifest(DATA).synthetic is True

    def test_an_edited_file_is_detected(self, tmp_path):
        """The failure this exists for: someone "just fixing" a row by hand."""
        import shutil

        root = tmp_path / "data"
        shutil.copytree(DATA, str(root))
        target = root / "anomalies" / "quotes_crossed_book.csv"
        target.write_text(
            target.read_text(encoding="utf-8").replace("62010", "62011"),
            encoding="utf-8",
        )
        report = md.verify_manifest(str(root))
        assert not report.ok
        assert any("CONTENT CHANGED" in problem for problem in report.problems)
        with pytest.raises(md.ManifestError):
            report.raise_if_bad()

    def test_a_missing_file_is_detected(self, tmp_path):
        import shutil

        root = tmp_path / "data"
        shutil.copytree(DATA, str(root))
        os.remove(str(root / "ohlcv" / "BYBIT_SPOT_SOL_USDT_1H.csv.gz"))
        report = md.verify_manifest(str(root))
        assert not report.ok
        assert any("missing" in problem for problem in report.problems)

    def test_recompression_is_not_reported_as_corruption(self, tmp_path):
        """Re-gzipping changes every byte and no rows.

        Calling that corruption trains people to ignore this check, which is the
        only way a check like this actually fails.
        """
        import shutil

        root = tmp_path / "data"
        shutil.copytree(DATA, str(root))
        target = root / "ohlcv" / "BYBIT_SPOT_SOL_USDT_1H.csv.gz"
        raw = gzip.decompress(target.read_bytes())
        buffer = io.BytesIO()
        with gzip.GzipFile(fileobj=buffer, mode="wb", compresslevel=1,
                           filename="", mtime=12345) as handle:
            handle.write(raw)
        target.write_bytes(buffer.getvalue())

        report = md.verify_manifest(str(root))
        assert report.ok, report.problems
        assert "ohlcv/BYBIT_SPOT_SOL_USDT_1H.csv.gz" in report.recompressed

    def test_a_missing_manifest_is_a_problem_not_a_pass(self, tmp_path):
        report = md.verify_manifest(str(tmp_path))
        assert not report.ok

    def test_a_corrupt_manifest_is_a_problem_not_a_pass(self, tmp_path):
        (tmp_path / "MANIFEST.json").write_text("{not json", encoding="utf-8")
        report = md.verify_manifest(str(tmp_path))
        assert not report.ok

    def test_every_corpus_file_is_listed(self, manifest):
        """Every file in THIS corpus root must be in THIS corpus's manifest.

        `data/real/` is a corpus in its own right, with its own MANIFEST.json
        and its own README — real Bitstamp data, not the synthetic corpus. It
        is verified by its own manifest, not by this one, and folding the two
        together would let a real file be checked against a synthetic hash.
        Nested roots are therefore skipped here and checked below.
        """
        on_disk = set()
        for folder, dirs, names in os.walk(DATA):
            dirs[:] = [
                d for d in dirs
                if not os.path.exists(os.path.join(folder, d, "MANIFEST.json"))
            ]
            for name in names:
                if name in ("MANIFEST.json", "README.md"):
                    continue
                on_disk.add(
                    os.path.relpath(os.path.join(folder, name), DATA).replace(os.sep, "/")
                )
        assert on_disk == set(manifest["files"]), (
            "a corpus file outside the manifest is a file nothing verifies"
        )

    def test_a_nested_corpus_root_verifies_against_its_own_manifest(self):
        """If data/real/ is present, it must verify — and declare itself REAL."""
        nested = os.path.join(DATA, "real")
        if not os.path.exists(os.path.join(nested, "MANIFEST.json")):
            pytest.skip("no data/real corpus in this checkout")
        report = md.verify_manifest(nested)
        assert report.problems == [], report.problems
        assert report.synthetic is False, (
            "data/real declares itself synthetic; that is the one field every "
            "report prints and it must be true"
        )


# ---------------------------------------------------------------------------
# provenance and structure
# ---------------------------------------------------------------------------


class TestProvenanceAndStructure:
    def test_the_readme_says_synthetic_on_its_first_line(self):
        """Provenance that is not unmissable is provenance that gets lost."""
        with open(os.path.join(DATA, "README.md"), encoding="utf-8") as handle:
            first = handle.readline()
        assert "SYNTHETIC" in first.upper()
        assert "make_dataset.py" in first

    def test_the_readme_explains_how_to_swap_in_real_data(self):
        with open(os.path.join(DATA, "README.md"), encoding="utf-8") as handle:
            text = handle.read()
        for needle in ("CoinAPI", "Bybit", "kline", "rehash", "anomalies"):
            assert needle in text, f"data/README.md does not mention {needle}"

    def test_the_readme_documents_every_anomaly_fixture(self):
        with open(os.path.join(DATA, "README.md"), encoding="utf-8") as handle:
            text = handle.read()
        for relpath, _kind, reason in anomaly_cases():
            assert os.path.basename(relpath) in text
            assert reason in text

    def test_the_module_imports_only_stdlib_numpy_and_config(self):
        """Dependencies point downward only (INTEGRATION_MAP §1).

        Importing `backtest` to reuse its `Bar` would drag persistence, risk,
        sizing, the client, the strategy and the engine in through one line.
        Checked by AST so the docstring that explains the rule does not trip it.
        """
        tree = ast.parse(
            open(os.path.join(REPO, "market_data.py"), encoding="utf-8").read()
        )
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(alias.name.split(".")[0] for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.add(node.module.split(".")[0])
        banned = {"backtest", "persistence", "risk_management", "position_sizing",
                  "bybit_connection", "trading_engine", "technical_analysis",
                  "main", "performance_analytics", "requests", "urllib",
                  "socket", "threading", "asyncio"}
        assert not (imported & banned), sorted(imported & banned)
        assert imported <= {
            "csv", "gzip", "hashlib", "io", "json", "logging", "math", "os",
            "re", "dataclasses", "typing", "numpy", "config", "__future__",
        }, f"unexpected imports: {sorted(imported)}"

    def test_the_module_does_not_read_the_environment(self):
        """`config.load()` is the sole environment reader (README invariants)."""
        source = open(os.path.join(REPO, "market_data.py"), encoding="utf-8").read()
        offenders = [
            (number, line.strip())
            for number, line in enumerate(source.splitlines(), 1)
            if ("os.getenv" in line or "os.environ" in line)
            and not line.lstrip().startswith("#")
            and "``" not in line
        ]
        assert offenders == [], offenders

    def test_the_generator_does_not_import_the_loader(self):
        """Independent implementations of the same contract.

        If the writer and the reader shared a timestamp function they would
        agree by construction, and every round-trip test in this file would be
        testing nothing.
        """
        tree = ast.parse(
            open(os.path.join(REPO, "tools", "make_dataset.py"),
                 encoding="utf-8").read()
        )
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(alias.name.split(".")[0] for alias in node.names)
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.add(node.module.split(".")[0])
        assert "market_data" not in imported

    def test_the_generator_and_the_loader_agree_on_the_timestamp_format(self):
        """Round-trip across the two independent implementations."""
        sys.path.insert(0, os.path.join(REPO, "tools"))
        import make_dataset

        for micros in (0, 1_709_251_200_000_000, 1_709_251_200_532_785):
            assert md.parse_timestamp(make_dataset.iso_utc(micros)) == micros

    def test_the_corpus_fits_in_a_zip(self):
        """A deliverability guard, not a safety invariant.

        Raised from 8 to 16 MiB in slice 34, deliberately and once: the real
        Binance ETH/SOL corpora (`data/real_multi_1d`, `data/real_multi_1h`) add
        ~2 MiB of genuine exchange history and took the total to 8.9 MiB. The
        ceiling exists to catch a corpus growing without anyone noticing, and it
        still does that — it is not a reason to refuse real data, and it was
        raised rather than deleted so the next unnoticed doubling still fails.
        """
        total = sum(
            os.path.getsize(os.path.join(folder, name))
            for folder, _dirs, names in os.walk(DATA) for name in names
        )
        assert total < 16 * 1024 * 1024, f"corpus is {total / 1048576:.1f} MiB"

    def test_regenerating_with_the_same_seed_is_byte_identical(self, tmp_path):
        """Without this the shipped sha256s are decoration.

        Generated at a reduced bar count so the test stays fast; the property
        under test is the RNG stream, the gzip header and the absence of any
        wall-clock field, none of which depend on length.
        """
        sys.path.insert(0, os.path.join(REPO, "tools"))
        import make_dataset

        first = make_dataset.generate(str(tmp_path / "a"), seed=7, bars=200)
        second = make_dataset.generate(str(tmp_path / "b"), seed=7, bars=200)
        assert {k: v["sha256"] for k, v in first["files"].items()} == \
               {k: v["sha256"] for k, v in second["files"].items()}

    def test_a_different_seed_gives_different_data(self, tmp_path):
        sys.path.insert(0, os.path.join(REPO, "tools"))
        import make_dataset

        first = make_dataset.generate(str(tmp_path / "a"), seed=7, bars=200)
        second = make_dataset.generate(str(tmp_path / "b"), seed=8, bars=200)
        key = "ohlcv/BYBIT_SPOT_BTC_USDT_1H.csv.gz"
        assert first["files"][key]["sha256"] != second["files"][key]["sha256"]

    def test_the_generator_refuses_to_ship_a_mislabelled_regime(self):
        """The guard that caught a CRASH phase finishing +46%."""
        sys.path.insert(0, os.path.join(REPO, "tools"))
        import make_dataset

        spec = make_dataset.SYMBOLS[0]
        # Long enough to reach STRONG_TREND: the first regime is declared flat,
        # and a flat regime stays flat when you invert it.
        bars = make_dataset.build_bars(spec, make_dataset.Rng(1), 1_700)
        # Invert every bar's return: whatever the labels said, they are now wrong.
        flipped = [bar._replace(open=bar.close, close=bar.open) for bar in bars]
        with pytest.raises(make_dataset.RegimeMismatch):
            make_dataset.assert_regimes_are_what_they_claim(spec.symbol_id, flipped)
