"""Is this corpus allowed to be Stage 1 evidence? One question, answered explicitly.

WHY THIS EXISTS
===============
The failure mode this prevents has a name: *"we ran Stage 1 on whatever CSV was
in the folder."*

It is not hypothetical here. `data/ohlcv/` contains
`BYBIT_SPOT_ETH_USDT_1H.csv.gz` and `BYBIT_SPOT_SOL_USDT_1H.csv.gz` — 5,000 bars
each, correct CoinAPI-shaped headers, plausible prices. A future session looking
for "multi-asset data" would find them immediately. They are **synthetic**,
generated by `tools/make_dataset.py` from a stochastic model, and any Sharpe or
win rate measured on them is a property of the generator.

So this module answers, per corpus, in a field rather than by implication:

    eligible_for_stage1 : bool
    ineligible_reasons  : list[str]   -- never empty when False

ELIGIBILITY IS NOT EDGE
=======================
A corpus marked eligible is a set of bars a measurement may legitimately be run
*against*. It says nothing about whether any signal times them. Nothing here
reopens `RESEARCH_CLOSE_STAGE1.md`, clears a signal, changes M1/M2, or touches
`ProjectStatus.cleared_edge_signal`. The BTC daily corpus is eligible, has 2,564
bars, and produced an ABSENT reading — eligibility and edge are different
questions and this module only answers the first.

HOW IT DECIDES
==============
It keys on the convention the repository already has rather than inventing a
second one. Every corpus directory carries a `MANIFEST.json` with a `synthetic`
boolean and a `bar_seconds` integer; the real corpora additionally carry a
`source.exchange`. That is the ground truth, not the directory name — a folder
called `real_something` proves nothing.

`is_synthetic` is checked **first and independently**. There is no combination of
other fields that can make a synthetic corpus eligible, and
`tests/test_data_contract.py` asserts that by forcing every other field to a
passing value.

FAIL CLOSED
===========
An unreadable manifest, an unparseable file, a missing directory, an unknown
interval: all produce `eligible_for_stage1: False` with a recorded reason. The
answer to "may I use this?" defaults to no, and the answer is never a shrug.
"""
from __future__ import annotations

import csv
import gzip
import io
import math
import json
import logging
import os
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import market_data as md

logger = logging.getLogger(__name__)

__all__ = [
    "CorpusRecord",
    "scan_corpus",
    "scan_all",
    "build_report",
    "MIN_BARS_DAILY",
    "MIN_BARS_INTRADAY",
    "REQUIRED_COLUMNS",
    "REPORT_SCHEMA",
    "interval_label_for",
    "min_bars_for",
]

#: Frozen in EDGE.md §13b **before** the scanner existed, so the threshold could
#: not be chosen to make a particular corpus pass.
#:
#: 500 daily bars is roughly two years and is the floor at which
#: `edge_measurement`'s four walk-forward folds are not absurd. 2000 intraday is
#: the mission's recommended default.
#:
#: These are a FLOOR FOR ELIGIBILITY, not a sufficiency claim. The BTC daily
#: corpus has 2,564 bars, clears this comfortably, and still returned ABSENT.
#: Sample size was never the problem — see EDGE.md §6d (H25), where a 43x range
#: of trade counts moved the percentiles by nothing.
MIN_BARS_DAILY = 500
MIN_BARS_INTRADAY = 2000

#: The CoinAPI-shaped schema every OHLCV file in this repository uses.
REQUIRED_COLUMNS = (
    "time_period_start", "price_open", "price_high", "price_low",
    "price_close", "volume_traded",
)

#: Bumped to /2 in slice 34. Real ETH and SOL corpora arrived alongside the
#: pre-existing *synthetic* ETH and SOL files, so a flat list of symbol names
#: became ambiguous: `non_btc_synthetic_symbols_present: ["ETH_USDT"]` and
#: `non_btc_real_symbols: ["ETH_USDT"]` are both true at once and name different
#: files. `non_btc_synthetic_symbols_by_corpus` disambiguates by path, which is
#: the thing a reader actually needs in order not to measure the wrong one.
REPORT_SCHEMA = "data_intake/2"

#: Corpus directories this repository ships. Discovered directories are added at
#: scan time; this tuple only fixes the order of the well-known ones so the
#: report reads predictably.
KNOWN_CORPORA = (
    "data/real_1d", "data/real_4h", "data/real",
    "data/ohlcv", "data/orderbook", "data/quotes", "data/anomalies",
)

_BTC_TOKENS = ("BTC", "XBT")


def interval_label_for(bar_seconds: Optional[int]) -> str:
    """A human label, or ``unknown``. Never a guess from a filename."""
    if not bar_seconds:
        return "unknown"
    return {
        60: "1m", 300: "5m", 900: "15m", 1800: "30m",
        3600: "1H", 14400: "4H", 86400: "D", 604800: "W",
    }.get(int(bar_seconds), "unknown")


def min_bars_for(bar_seconds: Optional[int]) -> int:
    """The frozen threshold that applies to this resolution."""
    if bar_seconds and int(bar_seconds) >= 86400:
        return MIN_BARS_DAILY
    return MIN_BARS_INTRADAY


#: The only interval strings a MANIFEST may use in place of `bar_seconds`.
#: A closed vocabulary, not a parser: an unrecognised label stays `unknown`
#: and the corpus stays ineligible. Added in slice 55, when the human-fetched
#: Binance USDT-M corpora arrived describing themselves as `"interval": "1d"`
#: rather than `"bar_seconds": 86400`.
_INTERVAL_SECONDS = {
    "1m": 60, "5m": 300, "15m": 900, "30m": 1800,
    "1h": 3600, "2h": 7200, "4h": 14400, "8h": 28800,
    "1d": 86400, "1w": 604800,
}


def manifest_bar_seconds(manifest: Optional[Dict[str, Any]]) -> Optional[int]:
    """Bar length from a MANIFEST, in either accepted vocabulary.

    `bar_seconds` is authoritative when present. Otherwise a lowercase
    `interval` label is looked up in the closed table above. Anything else
    returns ``None``, which keeps the corpus ineligible — a corpus that cannot
    say how long its bars are is not evidence.
    """
    if not manifest:
        return None
    explicit = manifest.get("bar_seconds")
    if explicit:
        try:
            return int(explicit)
        except (TypeError, ValueError):
            return None
    label = manifest.get("interval")
    if isinstance(label, str):
        return _INTERVAL_SECONDS.get(label.strip().lower())
    return None


def manifest_exchange(manifest: Optional[Dict[str, Any]]) -> str:
    """The venue a MANIFEST attributes its data to, or ``""``.

    Two shapes are accepted and no others:

    * ``source: {"exchange": "BINANCE", ...}`` — the original corpora;
    * ``venue: "binance_usdtm"`` **together with** a non-empty ``source``
      naming how it was fetched — the slice-55 funding and linear corpora.

    The second form requires both fields precisely so that a bare `venue`
    string cannot confer provenance on its own. This function says nothing
    about `synthetic`; that check stands alone and comes first at every call
    site.
    """
    if not manifest:
        return ""
    source = manifest.get("source")
    if isinstance(source, dict):
        return str(source.get("exchange") or "")
    venue = manifest.get("venue")
    if isinstance(venue, str) and venue.strip() and isinstance(source, str) \
            and source.strip():
        return venue.strip()
    return ""


@dataclass
class CorpusRecord:
    """One corpus, and whether Stage 1 may use it."""

    path: str
    exists: bool = False
    interval_label: str = "unknown"
    is_synthetic: bool = False
    is_real_exchange_ohlcv: bool = False
    symbols: List[str] = field(default_factory=list)
    bar_count: Optional[int] = None
    loadable_bar_count: Optional[int] = None
    rejected_rows: Optional[int] = None
    timestamp_policy: str = "unknown"
    required_columns_ok: bool = False
    gap_policy_result: str = "unknown"
    min_bars_for_stage1: int = MIN_BARS_INTRADAY
    eligible_for_stage1: bool = False
    ineligible_reasons: List[str] = field(default_factory=list)

    def as_dict(self) -> Dict[str, Any]:
        return asdict(self)


def _load_manifest_file(path: str) -> Optional[Dict[str, Any]]:
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as handle:
            loaded = json.load(handle)
        return loaded if isinstance(loaded, dict) else None
    except Exception as exc:  # noqa: BLE001
        logger.warning("unreadable manifest %s: %s", path, exc)
        return None


def _read_manifest(directory: str) -> Optional[Dict[str, Any]]:
    """This corpus's manifest, or the one governing it from one level up.

    The repository's actual layout has to be respected here rather than assumed.
    `data/real_1d/MANIFEST.json` describes `data/real_1d`, but `data/ohlcv`,
    `data/orderbook`, `data/quotes` and `data/anomalies` have **no manifest of
    their own** — they are all covered by `data/MANIFEST.json`, which says
    `synthetic: true`.

    Getting this wrong is not cosmetic. Without the parent lookup, `data/ohlcv`
    reports `is_synthetic: false` and the report's synthetic-symbol list comes
    back empty — so it would fail to say that the ETH and SOL files on disk are
    generated. That is the single most important sentence this report exists to
    print, and the first version of this function did not print it.
    """
    own = _load_manifest_file(os.path.join(directory, "MANIFEST.json"))
    if own is not None:
        return own
    parent = os.path.dirname(os.path.abspath(directory))
    inherited = _load_manifest_file(os.path.join(parent, "MANIFEST.json"))
    if inherited is not None:
        logger.debug("%s inherits provenance from %s/MANIFEST.json",
                     directory, parent)
    return inherited


def _ohlcv_files(directory: str) -> List[str]:
    ohlcv_dir = os.path.join(directory, "ohlcv")
    search = ohlcv_dir if os.path.isdir(ohlcv_dir) else directory
    if not os.path.isdir(search):
        return []
    return sorted(
        os.path.join(search, name)
        for name in os.listdir(search)
        if name.endswith((".csv", ".csv.gz"))
    )


def _open_text(path: str) -> io.TextIOBase:
    if path.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8", newline="")
    return open(path, "rt", encoding="utf-8", newline="")


def _symbol_from_filename(name: str) -> str:
    """`BITSTAMP_SPOT_BTC_USD_1D.csv.gz` -> `BTC_USD`; `""` if it does not match.

    Used only for reporting which instruments a corpus covers. It is never an
    input to eligibility — a filename is not evidence about provenance.

    Returning `""` for a non-conforming name matters more than it looks. The
    corpus convention is `EXCHANGE_TYPE_BASE_QUOTE_INTERVAL`, five parts. The
    files in `data/anomalies/` are named for their defect
    (`ohlcv_high_low_not_bracketing.csv`) and several have perfectly valid
    headers, because they are malformed in their *values*. An earlier version of
    this function split them anyway and invented instruments called `low_not`
    and `of_order`, which then appeared in the report's synthetic-symbol summary
    as though they were tradable pairs. A parser that cannot recognise a name
    should say so, not guess.
    """
    stem = os.path.basename(name).split(".")[0]
    parts = stem.split("_")
    # Five parts alone is not enough: `ohlcv_high_low_not_bracketing` has
    # exactly five and yielded the phantom instrument `low_not`. The convention's
    # first two tokens are the exchange and the product type and are always
    # upper case (`BITSTAMP_SPOT_...`); every anomaly file is named in lower case
    # (`ohlcv_...`, `l2_...`, `quotes_...`). That is the discriminator.
    if len(parts) < 5 or not parts[0].isupper() or not parts[1].isupper():
        return ""
    return "_".join(parts[2:4])


_UTC_SUFFIXES = ("Z", "+00:00", "+0000")

_LOADABLE_CACHE: Dict[Tuple[str, int, int], Tuple[Optional[int], Optional[int]]] = {}


def _loadable_rows(path: str) -> Tuple[Optional[int], Optional[int]]:
    """Return ``(bars the real loader accepts, rows it rejects)``.

    Counting CSV rows answers "how much is in the file". It does not answer
    "how much can Stage 1 actually read", and slice 38 is the reason the two
    are now measured separately: a human-supplied extension to the Bitstamp
    daily corpus wrote ``+00:00`` instead of ``Z`` and left ``trades_count``
    blank, ``market_data.load_ohlcv`` rejected all 571 new bars, and this
    report went on calling the corpus 3,135 bars and eligible. A measurement
    run on it would have silently used the old truncated window and been
    reported as the full history.

    So the contract now asks the loader itself. Importing ``market_data`` here
    is deliberate: any cheaper reimplementation would drift from the thing it
    is supposed to agree with, which is the whole defect.
    """
    try:
        stat = os.stat(path)
        key = (os.path.abspath(path), stat.st_mtime_ns, stat.st_size)
    except OSError as exc:
        logger.warning("cannot stat %s: %s", path, exc)
        return None, None
    if key in _LOADABLE_CACHE:
        return _LOADABLE_CACHE[key]

    try:
        import market_data
        load = market_data.load_ohlcv(path)
        result = (len(load.bars), len(load.rejections))
    except Exception as exc:  # noqa: BLE001
        logger.warning("loader could not read %s: %s", path, exc)
        result = (None, None)

    # Keyed on (path, mtime, size), so an edited file is re-read and an
    # unchanged one is not. The scan visits the 61,513-bar hourly corpus once
    # per corpus per call and the report calls it repeatedly; without this the
    # honest check costs more than the thing it protects, and a check people
    # switch off protects nothing.
    _LOADABLE_CACHE[key] = result
    return result


def _inspect_ohlcv(path: str) -> Tuple[Optional[int], bool, str, str]:
    """Return ``(bar_count, columns_ok, gap_result, timestamp_policy)``.

    Reads the whole file. These corpora are at most tens of thousands of rows,
    and a partial read could not answer the gap question honestly.
    """
    try:
        with _open_text(path) as handle:
            reader = csv.DictReader(handle)
            columns = set(reader.fieldnames or ())
            columns_ok = all(column in columns for column in REQUIRED_COLUMNS)
            if not columns_ok:
                return None, False, "unknown", "unknown"

            stamps: List[str] = []
            for row in reader:
                stamps.append((row.get("time_period_start") or "").strip())
    except Exception as exc:  # noqa: BLE001
        logger.warning("unreadable OHLCV %s: %s", path, exc)
        return None, False, "unknown", "unknown"

    if not stamps:
        return 0, columns_ok, "unknown", "unknown"

    # EVERY row, not the first one. Sampling stamps[0] is how a file that
    # starts in one spelling and continues in another reported "UTC" while the
    # loader was throwing the second half away.
    policy = ("UTC" if all(s.endswith(_UTC_SUFFIXES) for s in stamps)
              else "unknown")
    if len(set(stamps)) != len(stamps):
        return len(stamps), columns_ok, "fail", policy
    # Not lexicographic: the suffixes above have different widths, so string
    # order is only accidentally date order. Compare the date-time prefix.
    keys = [s[:19] for s in stamps]
    if any(b <= a for a, b in zip(keys, keys[1:])):
        return len(stamps), columns_ok, "fail", policy
    return len(stamps), columns_ok, "pass", policy


def scan_corpus(path: str, *, repo_root: Optional[str] = None) -> CorpusRecord:
    """Classify one corpus directory. Never raises; failure is a recorded reason."""
    root = repo_root or os.path.dirname(os.path.abspath(__file__))
    absolute = path if os.path.isabs(path) else os.path.join(root, path)
    record = CorpusRecord(path=path)
    reasons = record.ineligible_reasons

    if not os.path.isdir(absolute):
        record.exists = False
        reasons.append("path does not exist")
        return record
    record.exists = True

    manifest = _read_manifest(absolute)
    if manifest is None:
        reasons.append("no readable MANIFEST.json — provenance cannot be established")
    else:
        record.is_synthetic = bool(manifest.get("synthetic", False))
        exchange = manifest_exchange(manifest)
        record.is_real_exchange_ohlcv = (
            not record.is_synthetic and bool(exchange))
        bar_seconds = manifest_bar_seconds(manifest)
        record.interval_label = interval_label_for(bar_seconds)
        record.min_bars_for_stage1 = min_bars_for(bar_seconds)

    # The synthetic check stands alone and comes first. No combination of the
    # fields below can overturn it.
    if record.is_synthetic:
        reasons.append(
            "corpus is SYNTHETIC (MANIFEST.synthetic is true) — generated data "
            "is never Stage 1 evidence")

    files = _ohlcv_files(absolute)
    if not files:
        reasons.append("no OHLCV files found — not an OHLCV corpus")
    else:
        counts, oks, gaps, policies = [], [], [], []
        loadable: List[Optional[int]] = []
        rejected: List[Optional[int]] = []
        named: List[str] = []
        for one in files:
            count, ok, gap, policy = _inspect_ohlcv(one)
            counts.append(count)
            oks.append(ok)
            gaps.append(gap)
            policies.append(policy)
            if ok:
                good, bad = _loadable_rows(one)
                loadable.append(good)
                rejected.append(bad)
            # A symbol list is a claim about which instruments a corpus covers.
            # Only a file that actually parses as OHLCV supports such a claim —
            # otherwise `data/anomalies/ohlcv_high_low_not_bracketing.csv`
            # becomes an "instrument" called `low_not`, and that nonsense then
            # propagates into the synthetic-symbol summary.
            if ok:
                symbol = _symbol_from_filename(one)
                if symbol:
                    named.append(symbol)
        record.symbols = sorted(set(named))
        record.required_columns_ok = bool(oks) and all(oks)
        # The weakest file governs: a corpus is only as usable as its worst part.
        readable = [c for c in counts if c is not None]
        record.bar_count = min(readable) if readable else None
        good_counts = [c for c in loadable if c is not None]
        record.loadable_bar_count = min(good_counts) if good_counts else None
        bad_counts = [c for c in rejected if c is not None]
        record.rejected_rows = sum(bad_counts) if bad_counts else (
            0 if loadable and all(c is not None for c in rejected) else None)
        record.gap_policy_result = (
            "fail" if "fail" in gaps else
            "pass" if gaps and all(g == "pass" for g in gaps) else "unknown")
        record.timestamp_policy = (
            "UTC" if policies and all(p == "UTC" for p in policies) else "unknown")

        if not record.required_columns_ok:
            reasons.append(
                "required OHLCV columns missing "
                f"({', '.join(REQUIRED_COLUMNS)})")
        if record.gap_policy_result != "pass":
            reasons.append(
                f"timestamp gap policy: {record.gap_policy_result} "
                "(need strictly increasing, no duplicates)")
        if record.required_columns_ok:
            if record.rejected_rows is None:
                reasons.append(
                    "the loader could not read this corpus at all — "
                    "row count alone is not evidence Stage 1 can use it")
            elif record.rejected_rows:
                reasons.append(
                    f"{record.rejected_rows} of {record.bar_count} rows are "
                    f"rejected by market_data.load_ohlcv (only "
                    f"{record.loadable_bar_count} bars would actually load) — "
                    "a corpus Stage 1 can only partly read is not eligible, "
                    "because the part it drops is invisible in the results")

    if not record.is_real_exchange_ohlcv and not record.is_synthetic:
        reasons.append(
            "provenance not established as real exchange OHLCV "
            "(MANIFEST needs synthetic=false and a source.exchange)")
    if record.interval_label == "unknown":
        reasons.append("bar interval unknown — MANIFEST.bar_seconds missing or unrecognised")
    if record.bar_count is None:
        reasons.append("bar count unreadable")
    elif record.bar_count < record.min_bars_for_stage1:
        reasons.append(
            f"only {record.bar_count} bars; Stage 1 needs "
            f">= {record.min_bars_for_stage1} at {record.interval_label}")

    record.eligible_for_stage1 = (
        record.exists
        and not record.is_synthetic
        and record.is_real_exchange_ohlcv
        and record.required_columns_ok
        and record.interval_label != "unknown"
        and record.bar_count is not None
        and record.bar_count >= record.min_bars_for_stage1
        and record.gap_policy_result == "pass"
        and record.rejected_rows == 0
    )
    if record.eligible_for_stage1:
        # An eligible corpus must carry no reasons, and an ineligible one must
        # carry at least one. Silence is not an answer in either direction.
        record.ineligible_reasons = []
    elif not record.ineligible_reasons:
        record.ineligible_reasons = ["ineligible: no specific reason recorded"]
    return record


#: Columns a funding corpus must carry. `mark_price` is optional and unused by
#: Stage 1 — the join needs a time and a rate and nothing else.
FUNDING_REQUIRED_COLUMNS = ("funding_time", "symbol", "funding_rate")

#: Minimum funding prints for a symbol to be usable at Stage 1. A funding
#: series is not a bar series, so the OHLCV thresholds do not transfer: at 8h
#: prints, 1,000 rows is a little under a year, which is the shortest history
#: a daily-horizon study could take seriously.
MIN_FUNDING_PRINTS = 1_000


@dataclass
class FundingCorpusRecord:
    """One funding corpus, and whether Stage 1 may use it.

    A separate record type on purpose. Funding is not OHLCV, and the honest
    way to admit it was NOT to loosen `scan_corpus` until a rate series passed
    an OHLCV test — that would have made the OHLCV contract weaker for every
    corpus in order to accommodate one that is not OHLCV at all.
    """

    path: str
    exists: bool = True
    is_synthetic: bool = False
    exchange: str = ""
    interval_seconds: Optional[int] = None
    symbols: List[str] = field(default_factory=list)
    rows_by_symbol: Dict[str, int] = field(default_factory=dict)
    first_by_symbol: Dict[str, str] = field(default_factory=dict)
    last_by_symbol: Dict[str, str] = field(default_factory=dict)
    duplicate_timestamps: int = 0
    non_monotonic: int = 0
    non_finite_rates: int = 0
    eligible_for_stage1: bool = False
    ineligible_reasons: List[str] = field(default_factory=list)


def _funding_files(directory: str) -> List[str]:
    funding_dir = os.path.join(directory, "funding")
    search = funding_dir if os.path.isdir(funding_dir) else directory
    if not os.path.isdir(search):
        return []
    return sorted(
        os.path.join(search, name)
        for name in os.listdir(search)
        if name.endswith((".csv", ".csv.gz"))
    )


def scan_funding_corpus(path: str, *,
                        repo_root: Optional[str] = None) -> FundingCorpusRecord:
    """Classify one funding-rate corpus. Never raises; failure is a reason.

    The checks mirror the OHLCV contract's spirit rather than its columns:

    * `synthetic` stands alone and comes first — no other field can overturn it;
    * provenance must be attributed to a venue by the MANIFEST, not by a
      directory name;
    * every file must parse, carry the required columns, be strictly increasing
      in time, contain no duplicate timestamps, and carry finite rates;
    * every symbol needs at least `MIN_FUNDING_PRINTS` rows.

    What it deliberately does NOT do is repair anything. A gap in a funding
    series is a gap; the join policy in `signals/funding_carry_fade_v1.py`
    handles absence by declining to trade, never by forward-filling.
    """
    root = repo_root or os.path.dirname(os.path.abspath(__file__))
    absolute = path if os.path.isabs(path) else os.path.join(root, path)
    record = FundingCorpusRecord(path=path)
    reasons = record.ineligible_reasons

    if not os.path.isdir(absolute):
        record.exists = False
        reasons.append("path does not exist")
        return record

    manifest = _read_manifest(absolute)
    if manifest is None:
        reasons.append("no readable MANIFEST.json — provenance cannot be established")
    else:
        record.is_synthetic = bool(manifest.get("synthetic", False))
        record.exchange = manifest_exchange(manifest)
        record.interval_seconds = manifest_bar_seconds(manifest)

    if record.is_synthetic:
        reasons.append(
            "corpus is SYNTHETIC (MANIFEST.synthetic is true) — generated data "
            "is never Stage 1 evidence")
    if not record.exchange:
        reasons.append(
            "provenance not established (MANIFEST needs synthetic=false and "
            "either source.exchange or venue plus source)")

    files = _funding_files(absolute)
    if not files:
        reasons.append("no funding files found — not a funding corpus")

    for file_path in files:
        name = os.path.basename(file_path)
        try:
            with _open_text(file_path) as handle:
                rows = list(csv.DictReader(handle))
        except (OSError, csv.Error, UnicodeDecodeError) as exc:
            reasons.append(f"{name}: unreadable ({type(exc).__name__})")
            continue
        if not rows:
            reasons.append(f"{name}: empty")
            continue
        missing = [c for c in FUNDING_REQUIRED_COLUMNS if c not in rows[0]]
        if missing:
            reasons.append(f"{name}: missing columns {missing}")
            continue

        symbol = str(rows[0]["symbol"]).strip()
        stamps: List[str] = []
        previous: Optional[float] = None
        for row in rows:
            text = str(row["funding_time"]).strip()
            stamps.append(text)
            try:
                moment = md.parse_timestamp(text)
            except Exception:                              # noqa: BLE001
                reasons.append(f"{name}: unparseable funding_time {text!r}")
                moment = None
            if moment is not None:
                if previous is not None and moment <= previous:
                    record.non_monotonic += 1
                previous = moment
            try:
                rate = float(row["funding_rate"])
            except (TypeError, ValueError):
                record.non_finite_rates += 1
                continue
            if not math.isfinite(rate):
                record.non_finite_rates += 1

        record.duplicate_timestamps += len(stamps) - len(set(stamps))
        if symbol:
            record.symbols.append(symbol)
            record.rows_by_symbol[symbol] = len(rows)
            record.first_by_symbol[symbol] = stamps[0]
            record.last_by_symbol[symbol] = stamps[-1]
            if len(rows) < MIN_FUNDING_PRINTS:
                reasons.append(
                    f"{symbol}: only {len(rows)} funding prints; Stage 1 needs "
                    f">= {MIN_FUNDING_PRINTS}")

    record.symbols = sorted(set(record.symbols))
    if record.duplicate_timestamps:
        reasons.append(
            f"{record.duplicate_timestamps} duplicate funding timestamps")
    if record.non_monotonic:
        reasons.append(
            f"{record.non_monotonic} non-increasing funding timestamps")
    if record.non_finite_rates:
        reasons.append(f"{record.non_finite_rates} non-finite funding rates")

    record.eligible_for_stage1 = not reasons
    return record


def scan_all(*, repo_root: Optional[str] = None,
             corpora: Optional[Tuple[str, ...]] = None) -> List[CorpusRecord]:
    """Scan the well-known corpora plus any other directory under ``data/``."""
    root = repo_root or os.path.dirname(os.path.abspath(__file__))
    paths: List[str] = list(corpora if corpora is not None else KNOWN_CORPORA)
    data_dir = os.path.join(root, "data")
    if corpora is None and os.path.isdir(data_dir):
        for name in sorted(os.listdir(data_dir)):
            candidate = f"data/{name}"
            if os.path.isdir(os.path.join(data_dir, name)) and candidate not in paths:
                paths.append(candidate)
    return [scan_corpus(p, repo_root=root) for p in paths]


def build_report(*, repo_root: Optional[str] = None,
                 corpora: Optional[Tuple[str, ...]] = None) -> Dict[str, Any]:
    """The full report. Absence is stated, never left to be inferred."""
    records = scan_all(repo_root=repo_root, corpora=corpora)
    eligible = [r for r in records if r.eligible_for_stage1]

    # Real, non-BTC instruments. The point of computing this separately is that
    # ETH and SOL files DO exist on disk and are synthetic; a reader must not be
    # able to conclude multi-asset coverage from a filename.
    non_btc_real: List[str] = sorted({
        symbol for r in eligible for symbol in r.symbols
        if not any(token in symbol.upper() for token in _BTC_TOKENS)
    })
    synthetic_non_btc: List[str] = sorted({
        symbol for r in records if r.is_synthetic for symbol in r.symbols
        if not any(token in symbol.upper() for token in _BTC_TOKENS)
    })
    # Which corpus each synthetic non-BTC symbol lives in. Since slice 34 the
    # repository contains BOTH a real ETH_USDT and a synthetic one, so the name
    # alone no longer identifies a file. Answering "which ETH_USDT?" by path is
    # the difference between measuring the market and measuring a generator.
    synthetic_non_btc_by_corpus: Dict[str, List[str]] = {
        r.path: sorted(s for s in r.symbols
                       if not any(t in s.upper() for t in _BTC_TOKENS))
        for r in records if r.is_synthetic
        and any(not any(t in s.upper() for t in _BTC_TOKENS) for s in r.symbols)
    }
    real_non_btc_by_corpus: Dict[str, List[str]] = {
        r.path: sorted(s for s in r.symbols
                       if not any(t in s.upper() for t in _BTC_TOKENS))
        for r in eligible
        if any(not any(t in s.upper() for t in _BTC_TOKENS) for s in r.symbols)
    }

    return {
        "schema": REPORT_SCHEMA,
        "min_bars_for_stage1": {
            "daily": MIN_BARS_DAILY, "intraday": MIN_BARS_INTRADAY,
        },
        "corpora": [r.as_dict() for r in records],
        "stage1_eligible_corpus_paths": [r.path for r in eligible],
        "multi_asset_corpus_present": bool(non_btc_real),
        "non_btc_real_symbols": non_btc_real,
        "non_btc_real_symbols_by_corpus": real_non_btc_by_corpus,
        "non_btc_synthetic_symbols_present": synthetic_non_btc,
        "non_btc_synthetic_symbols_by_corpus": synthetic_non_btc_by_corpus,
        "note": (
            "Eligibility is NOT edge. An eligible corpus is a set of bars a "
            "measurement may legitimately be run against; it says nothing about "
            "whether any signal times them. Timing-skill research remains CLOSED "
            "— see RESEARCH_CLOSE_STAGE1.md."
        ),
    }
